version: "3"

services:
  store:
    build: .
    command: nodemon /srv/app/src/server.js
    volumes:
    - data:/var/tocq/db
    - ./src:/srv/app/src
    environment:
      DB_PATH: /var/tocq/db
      PORT: 3000
      HOST: 0.0.0.0
    ports:
    - 3000


volumes:
  data: